# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "add-integration-tests-try" ]
  pull_request:
    branches: [ "add-integration-tests-try" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    # Install Google Chrome
    - name: Install Google Chrome
      run: |
        - sudo apt update
        - sudo apt install -y wget unzip google-chrome-stable

    - name: Get Chrome Version
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f1-3)
        echo "Chrome version: $CHROME_VERSION"
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

    #Install ChromeDriver
    - name: Install Chromedriver
      run: |
        CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        echo "ChromeDriver version: $CHROME_DRIVER_VERSION"
        wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
  

  # Build project
    - name: Build the project
      run: mvn clean install -DskipTests

    # Run unit tests
    - name: Run unit tests
      run: mvn test

    # Run integration tests
    - name: Run integration tests (Selenium)
      run: mvn verify
