name: Java CI with Maven
on:
  push:
    branches: [ "add-integration-tests-try" ]
  pull_request:
    branches: [ "add-integration-tests-try" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip google-chrome-stable

      - name: Create drivers directory if it doesn't exist
        run: mkdir -p $GITHUB_WORKSPACE/drivers

      - name: Install Chromedriver
        run: |
          curl -L https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -o $GITHUB_WORKSPACE/drivers/chromedriver-linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver

      # Build project
      - name: Build the project
        run: mvn clean install -DskipTests

      # Run unit tests
      - name: Run unit tests
        run: mvn test

      # Run integration tests
      - name: Run integration tests (Selenium)
        run: mvn verify